import React from 'react'
import logo from '../assets/logo.png'

const About = () => {
  return (
    <div className="about max-w-container mx-auto py-[50px]">
      <div className="txt">
        <img src={logo} alt="logo" />
        <h2 className='text-[24px] font-bold pt-[30px]'>Our Vision</h2>
        <p className='text-justify pb-[20px] text-[#555]'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit sit cupiditate ullam! Tenetur rerum fugiat necessitatibus culpa quisquam temporibus enim voluptatem quis repellat, nam, praesentium eos accusamus at explicabo facere perferendis, excepturi saepe cupiditate in molestiae consequuntur. Incidunt explicabo doloremque impedit repellat, dignissimos consequatur! Molestias expedita neque reprehenderit amet, laborum aut blanditiis, reiciendis ea nemo debitis, eos vitae impedit maiores suscipit voluptates dolorum? Accusamus sint, incidunt, eum sed eaque molestiae provident laborum ea repellendus porro quod error dignissimos? Vel, ex corporis itaque dolorem repellendus praesentium, illum a eius blanditiis earum minima aliquid temporibus, inventore magnam? Libero eum fuga ullam neque animi expedita quasi ipsum tempore nulla quam, tempora esse quae optio voluptas commodi, minus vero laudantium consequuntur necessitatibus obcaecati? Quasi ad accusamus, perspiciatis veniam numquam doloribus, nostrum mollitia, facere est aspernatur at vitae assumenda quibusdam consequatur placeat iste praesentium? Recusandae temporibus doloremque obcaecati. Quod cumque suscipit quisquam magnam illo odio nemo quibusdam voluptatem perspiciatis. Reprehenderit nemo pariatur labore! Ipsum quia repellat atque enim recusandae, ipsa porro reprehenderit molestiae quod nesciunt tenetur ducimus praesentium distinctio architecto tempore veniam eveniet! Rerum quo blanditiis consequatur vero ad odio quas deleniti, ipsam necessitatibus earum aperiam nam amet possimus vel quasi illum, illo quam numquam laboriosam. Consequuntur numquam tempore itaque ipsam, laboriosam blanditiis commodi ut recusandae aliquam a, perferendis, voluptatibus rem facere ipsum quia! Eos provident voluptates incidunt, veniam repudiandae cumque sint earum consequuntur sequi labore? Ab explicabo repellat quis eligendi soluta officia delectus consequuntur optio animi voluptates architecto porro error asperiores, aliquid ex alias consequatur dignissimos, ducimus saepe, maxime ea officiis! Est repudiandae maxime id omnis quidem inventore voluptatum consequuntur reprehenderit architecto ullam nobis doloribus magni at, impedit iure quia animi iusto aspernatur quod dolores modi. Ipsum, est facilis quidem officia, facere iusto esse asperiores accusantium dolores fugiat consequuntur ad labore quod aut molestiae.</p>
        <h2 className='text-[24px] font-bold pt-[30px]'>Our Story</h2>
        <p className='text-justify pb-[20px] text-[#555]'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit sit cupiditate ullam! Tenetur rerum fugiat necessitatibus culpa quisquam temporibus enim voluptatem quis repellat, nam, praesentium eos accusamus at explicabo facere perferendis, excepturi saepe cupiditate in molestiae consequuntur. Incidunt explicabo doloremque impedit repellat, dignissimos consequatur! Molestias expedita neque reprehenderit amet, laborum aut blanditiis, reiciendis ea nemo debitis, eos vitae impedit maiores suscipit voluptates dolorum? Accusamus sint, incidunt, eum sed eaque molestiae provident laborum ea repellendus porro quod error dignissimos? Vel, ex corporis itaque dolorem repellendus praesentium, illum a eius blanditiis earum minima aliquid temporibus, inventore magnam? Libero eum fuga ullam neque animi expedita quasi ipsum tempore nulla quam, tempora esse quae optio voluptas commodi, minus vero laudantium consequuntur necessitatibus obcaecati? Quasi ad accusamus, perspiciatis veniam numquam doloribus, nostrum mollitia, facere est aspernatur at vitae assumenda quibusdam consequatur placeat iste praesentium? Recusandae temporibus doloremque obcaecati. Quod cumque suscipit quisquam magnam illo odio nemo quibusdam voluptatem perspiciatis. Reprehenderit nemo pariatur labore! Ipsum quia repellat atque enim recusandae, ipsa porro reprehenderit molestiae quod nesciunt tenetur ducimus praesentium distinctio architecto tempore veniam eveniet! Rerum quo blanditiis consequatur vero ad odio quas deleniti, ipsam necessitatibus earum aperiam nam amet possimus vel quasi illum, illo quam numquam laboriosam. Consequuntur numquam tempore itaque ipsam, laboriosam blanditiis commodi ut recusandae aliquam a, perferendis, voluptatibus rem facere ipsum quia! Eos provident voluptates incidunt, veniam repudiandae cumque sint earum consequuntur sequi labore? Ab explicabo repellat quis eligendi soluta officia delectus consequuntur optio animi voluptates architecto porro error asperiores, aliquid ex alias consequatur dignissimos, ducimus saepe, maxime ea officiis! Est repudiandae maxime id omnis quidem inventore voluptatum consequuntur reprehenderit architecto ullam nobis doloribus magni at, impedit iure quia animi iusto aspernatur quod dolores modi. Ipsum, est facilis quidem officia, facere iusto esse asperiores accusantium dolores fugiat consequuntur ad labore quod aut molestiae.</p>
        <h2 className='text-[24px] font-bold pt-[30px]'>Our Brands</h2>
        <p className='text-justify pb-[20px] text-[#555]'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit sit cupiditate ullam! Tenetur rerum fugiat necessitatibus culpa quisquam temporibus enim voluptatem quis repellat, nam, praesentium eos accusamus at explicabo facere perferendis, excepturi saepe cupiditate in molestiae consequuntur. Incidunt explicabo doloremque impedit repellat, dignissimos consequatur! Molestias expedita neque reprehenderit amet, laborum aut blanditiis, reiciendis ea nemo debitis, eos vitae impedit maiores suscipit voluptates dolorum? Accusamus sint, incidunt, eum sed eaque molestiae provident laborum ea repellendus porro quod error dignissimos? Vel, ex corporis itaque dolorem repellendus praesentium, illum a eius blanditiis earum minima aliquid temporibus, inventore magnam? Libero eum fuga ullam neque animi expedita quasi ipsum tempore nulla quam, tempora esse quae optio voluptas commodi, minus vero laudantium consequuntur necessitatibus obcaecati? Quasi ad accusamus, perspiciatis veniam numquam doloribus, nostrum mollitia, facere est aspernatur at vitae assumenda quibusdam consequatur placeat iste praesentium? Recusandae temporibus doloremque obcaecati. Quod cumque suscipit quisquam magnam illo odio nemo quibusdam voluptatem perspiciatis. Reprehenderit nemo pariatur labore! Ipsum quia repellat atque enim recusandae, ipsa porro reprehenderit molestiae quod nesciunt tenetur ducimus praesentium distinctio architecto tempore veniam eveniet! Rerum quo blanditiis consequatur vero ad odio quas deleniti, ipsam necessitatibus earum aperiam nam amet possimus vel quasi illum, illo quam numquam laboriosam. Consequuntur numquam tempore itaque ipsam, laboriosam blanditiis commodi ut recusandae aliquam a, perferendis, voluptatibus rem facere ipsum quia! Eos provident voluptates incidunt, veniam repudiandae cumque sint earum consequuntur sequi labore? Ab explicabo repellat quis eligendi soluta officia delectus consequuntur optio animi voluptates architecto porro error asperiores, aliquid ex alias consequatur dignissimos, ducimus saepe, maxime ea officiis! Est repudiandae maxime id omnis quidem inventore voluptatum consequuntur reprehenderit architecto ullam nobis doloribus magni at, impedit iure quia animi iusto aspernatur quod dolores modi. Ipsum, est facilis quidem officia, facere iusto esse asperiores accusantium dolores fugiat consequuntur ad labore quod aut molestiae.</p>
      </div>
    </div>
  )
}

export default About